### ISSUE TITLE
tests fail if IPv6 is disabled

### ISSUE THREAD

**Issue by sandrotosi** [haypo/trollius#8]
i have ipv6 disabled on this machine, which triggers:

```
Traceback (most recent call last):
  File "runtests.py", line 334, in <module>
    runtests()
  File "runtests.py", line 303, in runtests
    finder = TestsFinder(args.testsdir, includes, excludes)
  File "runtests.py", line 160, in __init__
    self.find_available_tests()
  File "runtests.py", line 167, in find_available_tests
    mods = [mod for mod, _ in load_modules(self._testsdir)]
  File "runtests.py", line 136, in load_modules
    mod = load_module(modname, sourcefile)
  File "runtests.py", line 98, in load_module
    return imp.load_source(modname, sourcefile)
  File "tests/test_tasks.py", line 16, in <module>
    from trollius import test_support as support
  File "/tmp/buildd/python-trollius-2.1~b1/trollius/test_support.py", line 133, in <module>
    IPV6_ENABLED = _is_ipv6_enabled()
  File "/tmp/buildd/python-trollius-2.1~b1/trollius/test_support.py", line 123, in _is_ipv6_enabled
    sock = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
  File "/usr/lib/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 97] Address family not supported by protocol
```

this is because there check is done on 

```
$ python -c "import socket; print socket.has_ipv6"
True
```

from the doc it appears has_ipv6 has a different meaning from what one might think: "This constant contains a boolean value which indicates if IPv6 is supported on this platform." - so yeah on Linux there is IPv6 support, still I dont have it enabled, so test_support fails

**Comment by jamadden** [comment]
Thank you for the report. Unfortunately this project is not maintained and not expecting to make any changes.
